### ISSUE TITLE
Safe validation script for mongodb schema

### ISSUE THREAD

**Issue by g00gol** [EDH-Top-16/edhtop16-v2#1]
**Is your feature request related to a problem? Please describe.**
Database content should always follow a strict guideline. e.g. if there exists a field for one document, there should exist the same field for all others. This is not the case right now.

We also don't have a script to back up the database.

**Describe the solution you'd like**
Write a script to iterate through each database item and:
1. return a list and number of invalid documents
2. run a backup script
3. ask for confirmation to fix these fields by giving them default values

**Additional context**
here is the return schema for tournaments:
```py
class Tournament(BaseModel):
    _id: str
    name: str
    profile: str
    decklist: str
    wins: int
    winsSwiss: int
    winsBracket: int
    winRate: float
    winRateSwiss: float
    winRateBracket: float
    draws: int
    losses: int
    lossesSwiss: int
    lossesBracket: int
    standing: int
    colorID: str
    commander: str
```

**Comment by g00gol** [comment]
@JasonQiu21 bumping priority for this issue. You've been assigned

**Comment by JasonQiu21** [comment]
https://github.com/EDH-Top-16/edhtop16/issues/53

also need to add duplicate detection/deletion
