### ISSUE TITLE
Replace zod with joi

### ISSUE THREAD

**Issue by g00gol** [EDH-Top-16/edhtop16-v2#12]
**Is your feature request related to a problem? Please describe.**
Just read over the joi documentation and saw that it was much more powerful than zod. Let's plan a refactor to joi

**Describe the solution you'd like**
Replace instances of zod with joi and change code to integrate with joi

**Additional context**

**Comment by rrdelaney** [comment]
No longer using either library for client-side validation. Instead using relay, closing out the issue!
