### ISSUE TITLE
Add a CI/CD for building frontend and backend

### ISSUE THREAD

**Issue by g00gol** [EDH-Top-16/edhtop16-v2#18]
**Is your feature request related to a problem? Please describe.**
We should build a pipeline for checking whether the site builds and deploys correctly

**Describe the solution you'd like**
Implement CI/CD to do so

**Additional context**

**Comment by JasonQiu21** [comment]
CI/CD created and deployed; there were some issues accessing v2 client side, @rrdelaney feel free to close this if you resolve that

**Comment by JasonQiu21** [comment]
@rrdelaney I think we can close this?
