### ISSUE TITLE
Update Github developer documentation

### ISSUE THREAD

**Issue by g00gol** [EDH-Top-16/edhtop16-v2#5]
**Is your feature request related to a problem? Please describe.**
Our README.md is a little outdated now that we have switched to Next.js + FastAPI.

**Describe the solution you'd like**
Edit the README.md to reflect the changes we made and explain what each folder houses and does. Consider having a separate README for `client/` and `server/`

**Comment by JasonQiu21** [comment]
should also add onboarding documentation somewhere, and I think readme is good
